// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwqudbxhgklmhoykhhxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cXVkYnhoZ2tsbWhveWtoaHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTY4MDYsImV4cCI6MjA2MTY3MjgwNn0.WmTTWpkERxk9tCG12rWMEJHiODWDAHliwXhXmTFiNBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);